# Generated by Django 3.2 on 2021-04-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=30)),
                ('arttype', models.CharField(choices=[('P', 'Painting'), ('S', 'Sketch'), ('O', 'Other'), ('N', 'None')], default='N', max_length=10)),
                ('saleStatus', models.BooleanField(db_column='Sale Status')),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('date', models.DateField(db_column='Date')),
                ('price', models.FloatField(db_column='Price')),
                ('desc', models.TextField(db_column='Description')),
                ('artImg', models.ImageField(db_column='Art_Img', upload_to='')),
            ],
            options={
                'db_table': 'Art',
            },
        ),
    ]
